version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=transactiondb'
      - 'POSTGRES_PASSWORD=user'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres-transactions-data:/var/lib/postgres-transactions-data/data
