spring:
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/transactiondb
    password: user
    username: user
  application:
    name: test_task
server:
  port: 8080
